import { LogoIcon } from "@/components/logo";
import type { PayslipBranding } from "@/lib/payslip/branding";

// Self-contained so the document renders in both server pages and the client
// live-preview (the shared org formatter is server-only).
function formatMoney(amount: number): string {
  return new Intl.NumberFormat("en-TZ", {
    style: "currency",
    currency: "TZS",
    maximumFractionDigits: 0,
  }).format(Number.isFinite(amount) ? amount : 0);
}

interface Line {
  code: string;
  name: string;
  amount: number;
}

export interface PayslipData {
  companyName: string;
  period: string;
  employeeName: string;
  employeeNumber: string;
  basicSalary: number;
  earnings: Line[];
  grossPay: number;
  deductions: Line[];
  totalDeductions: number;
  netPay: number;
  taxableIncome: number;
  paye: number;
  employerContributions: Line[];
  status: string;
  runId: string;
}

function Logo({
  url,
  className,
  style,
}: {
  url: string | null;
  className?: string;
  style?: React.CSSProperties;
}) {
  if (url) {
    // Employer-uploaded logo (public tenant-branding bucket).
    // eslint-disable-next-line @next/next/no-img-element
    return <img alt="Company logo" className={className} src={url} style={style} />;
  }
  return <LogoIcon className={className} style={style} />;
}

function Row({ label, value, sign = "" }: { label: string; value: number; sign?: string }) {
  return (
    <div className="flex justify-between">
      <span>{label}</span>
      <span className="font-mono">{sign}{formatMoney(value)}</span>
    </div>
  );
}

/** Renders a payslip in the company's chosen template, brand colours and logo.
 *  Pure/server-safe; the enclosing page owns print styling. */
export function PayslipDocument({
  data,
  branding,
}: {
  data: PayslipData;
  branding: PayslipBranding;
}) {
  const brand = branding.brandColor;
  const accent = branding.accentColor;

  const Earnings = (
    <section>
      <h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        Earnings
      </h2>
      <div className="flex flex-col gap-1">
        <Row label="Basic salary" value={data.basicSalary} />
        {data.earnings.map((e) => (
          <Row key={e.code} label={e.name} value={e.amount} />
        ))}
        <div className="mt-1 flex justify-between border-t pt-1 font-medium">
          <span>Gross pay</span>
          <span className="font-mono">{formatMoney(data.grossPay)}</span>
        </div>
      </div>
    </section>
  );

  const Deductions = (
    <section>
      <h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        Deductions
      </h2>
      <div className="flex flex-col gap-1">
        {data.deductions.length === 0 && (
          <span className="text-muted-foreground">None</span>
        )}
        {data.deductions.map((d) => (
          <Row key={d.code} label={d.name} value={d.amount} sign="−" />
        ))}
        <div className="mt-1 flex justify-between border-t pt-1 font-medium">
          <span>Total deductions</span>
          <span className="font-mono">−{formatMoney(data.totalDeductions)}</span>
        </div>
      </div>
    </section>
  );

  const Employer = data.employerContributions.length > 0 && (
    <section>
      <h2 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        Employer contributions (not deducted from pay)
      </h2>
      <div className="flex flex-col gap-1 text-xs text-muted-foreground">
        {data.employerContributions.map((c) => (
          <Row key={c.code} label={c.name} value={c.amount} />
        ))}
      </div>
    </section>
  );

  const Footer = (
    <footer className="border-t pt-3 text-[10px] text-muted-foreground">
      {branding.footerNote && <p className="mb-1">{branding.footerNote}</p>}
      Generated by Stellix · run {data.runId.slice(0, 8)} · status {data.status} ·
      amounts in TZS. Reproducible from the run&apos;s immutable calculation snapshot.
    </footer>
  );

  // ── Template: MODERN — coloured header band ────────────────────────────
  if (branding.template === "modern") {
    return (
      <article className="flex flex-col overflow-hidden rounded-xl border bg-background text-sm print:border-none">
        <header
          className="flex items-center justify-between p-6 text-white"
          style={{ backgroundColor: brand }}
        >
          <div className="flex items-center gap-3">
            <Logo url={branding.logoUrl} className="size-8 object-contain" />
            <div>
              <p className="font-bold leading-tight">{data.companyName}</p>
              <p className="text-xs opacity-80">Payslip · {data.period}</p>
            </div>
          </div>
          <div className="text-right text-xs">
            <p className="font-medium">{data.employeeName}</p>
            <p className="font-mono opacity-80">{data.employeeNumber}</p>
          </div>
        </header>
        <div className="flex flex-col gap-5 p-6">
          {Earnings}
          {Deductions}
          <section className="rounded-lg p-4 text-white" style={{ backgroundColor: accent }}>
            <div className="flex items-center justify-between text-base font-semibold">
              <span>Net pay</span>
              <span className="font-mono">{formatMoney(data.netPay)}</span>
            </div>
            <p className="mt-1 text-xs opacity-80">
              Taxable {formatMoney(data.taxableIncome)} · PAYE {formatMoney(data.paye)}
            </p>
          </section>
          {Employer}
          {Footer}
        </div>
      </article>
    );
  }

  // ── Template: BOLD — large net-pay hero ────────────────────────────────
  if (branding.template === "bold") {
    return (
      <article className="flex flex-col gap-5 rounded-xl border bg-background p-8 text-sm print:border-none">
        <header className="flex items-center justify-between">
          <Logo url={branding.logoUrl} className="size-8 object-contain" style={{ color: brand }} />
          <div className="text-right text-xs">
            <p className="font-medium">{data.employeeName}</p>
            <p className="font-mono text-muted-foreground">{data.employeeNumber}</p>
          </div>
        </header>
        <div
          className="rounded-xl p-6 text-white"
          style={{ background: `linear-gradient(135deg, ${brand}, ${accent})` }}
        >
          <p className="text-xs uppercase tracking-widest opacity-80">
            {data.companyName} · Net pay · {data.period}
          </p>
          <p className="mt-1 font-mono text-4xl font-bold tracking-tight">
            {formatMoney(data.netPay)}
          </p>
        </div>
        {Earnings}
        {Deductions}
        <section className="text-xs text-muted-foreground">
          Taxable income {formatMoney(data.taxableIncome)} · PAYE {formatMoney(data.paye)}
        </section>
        {Employer}
        {Footer}
      </article>
    );
  }

  // ── Template: MINIMAL — mono, colour only on net pay ───────────────────
  if (branding.template === "minimal") {
    return (
      <article className="flex flex-col gap-5 bg-background p-8 text-sm">
        <header className="flex items-center justify-between border-b pb-3">
          <div className="flex items-center gap-2">
            <Logo url={branding.logoUrl} className="size-5 object-contain" />
            <span className="font-medium">{data.companyName}</span>
          </div>
          <span className="font-mono text-xs text-muted-foreground">{data.period}</span>
        </header>
        <div className="flex justify-between text-xs text-muted-foreground">
          <span>{data.employeeName}</span>
          <span className="font-mono">{data.employeeNumber}</span>
        </div>
        {Earnings}
        {Deductions}
        <section className="flex items-center justify-between border-t pt-3 text-base font-semibold">
          <span>Net pay</span>
          <span className="font-mono" style={{ color: accent }}>
            {formatMoney(data.netPay)}
          </span>
        </section>
        <p className="text-xs text-muted-foreground">
          Taxable {formatMoney(data.taxableIncome)} · PAYE {formatMoney(data.paye)}
        </p>
        {Employer}
        {Footer}
      </article>
    );
  }

  // ── Template: CLASSIC — traditional ruled payslip ──────────────────────
  return (
    <article className="flex flex-col gap-5 rounded-xl border bg-background p-8 text-sm print:border-none">
      <header className="flex items-center justify-between border-b-2 pb-4" style={{ borderColor: brand }}>
        <Logo url={branding.logoUrl} className="size-8 object-contain" style={{ color: brand }} />
        <div className="text-center">
          <p className="text-base font-bold" style={{ color: brand }}>{data.companyName}</p>
          <p className="text-xs uppercase tracking-widest text-muted-foreground">
            Payslip · {data.period}
          </p>
        </div>
        <div className="text-right text-xs">
          <p className="font-medium">{data.employeeName}</p>
          <p className="font-mono text-muted-foreground">{data.employeeNumber}</p>
        </div>
      </header>
      {Earnings}
      {Deductions}
      <section
        className="flex items-center justify-between border-y-2 py-2 text-base font-semibold"
        style={{ borderColor: brand }}
      >
        <span>Net pay</span>
        <span className="font-mono">{formatMoney(data.netPay)}</span>
      </section>
      <p className="text-xs text-muted-foreground">
        Taxable income {formatMoney(data.taxableIncome)} · PAYE {formatMoney(data.paye)}
      </p>
      {Employer}
      {Footer}
    </article>
  );
}
